[package]
name = "makima"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = { version = "0.12.1", features = ["tokio", "serde"] }
tokio = { version = "1.28.1", features = ["full"] }
serde = { version = "1.0.163", features = ["derive"] }
tokio-stream = "0.1.14"
tokio-udev = "0.9.1"
hyprland = "<=0.3.9"
toml = "0.7.3"
home = "<=0.5.5"
