#SAMPLE CONFIG FILE FOR PLAYSTATION 2 CONTROLLERS
#Put this in ~/.config/makima and rename it to the exact name of the device as shown by the 'evtest' command, including spaces and capitalization.
#You can find all the available keycodes in /usr/include/linux/input-event-codes.h
#If you're not sure which keycode corresponds to which key, you can run 'evtest', select your device and press the corresponding key/button.
#This config file is tested for DualShock 2 controllers. The "analog" LED on your controller has to be turned on or this daemon won't work properly. When using a different controller, if no specific config file for your device is available, change the keycodes on the left according to those of your controller (evtest is your friend again).

[bindings.keys]
#CONTROLLER   MOUSE/KEYBOARD BINDINGS
BTN_TRIGGER = ["KEY_LEFTMETA", "KEY_J"] #triangle
BTN_THUMB = ["KEY_ENTER"] #circle
BTN_THUMB2 = ["KEY_LEFTSHIFT"] #X
BTN_TOP = ["KEY_LEFTMETA"] #square
BTN_BASE2 = ["KEY_LEFTMETA", "KEY_L"] #R1
BTN_PINKIE = ["KEY_LEFTMETA", "KEY_LEFTSHIFT", "KEY_L"] #R2
BTN_BASE = ["KEY_LEFTMETA", "KEY_K"] #L1
BTN_TOP2 = ["KEY_LEFTMETA", "KEY_LEFTSHIFT", "KEY_K"] #L2
BTN_BASE4 = ["KEY_LEFTMETA", "KEY_D"] #start
BTN_BASE3 = ["KEY_ESC"] #select
BTN_BASE6 = ["KEY_LEFTMETA", "KEY_Q"] #R3
BTN_BASE5 = ["BTN_MIDDLE"] #L3

[bindings.axis]
BTN_DPAD_UP = ["KEY_UP"] #directional pad up
BTN_DPAD_RIGHT = ["KEY_RIGHT"] #directional pad right
BTN_DPAD_DOWN = ["KEY_DOWN"] #directional pad down
BTN_DPAD_LEFT = ["KEY_LEFT"] #directional pad left

[settings]
CURSOR_SENSITIVITY = "6" #lower value is higher sensitivity, minimum 1
SCROLL_SENSITIVITY = "6" #lower value is higher sensitivity, minimum 1
CURSOR_STICK = "left" #left, right or none
SCROLL_STICK = "right" #left, right or none
DEADZONE = "5" #integer between 0 and 128, bigger number is wider deadzone, default 5
GRAB_DEVICE = "false" #gain exclusivity on the device
