#SAMPLE CONFIG FILE FOR SWITCH JOYCONS
#Put this in ~/.config/makima and rename it to the exact name of the device as shown by the 'evtest' command, including spaces and capitalization. Omit "/" if present.
#You can find all the available keycodes in /usr/include/linux/input-event-codes.h
#If you're not sure which keycode corresponds to which key, you can run 'evtest', select your device and press the corresponding key/button.
#Relative and absolute axis events are hard coded, for example use RSTICK_UP, RSTICK_DOWN etc to rebind your analog stick.
#This config file is tested for Switch Joycons (Left and Right). When using a different controller, if no specific config file for your device is available, change the keycodes on the left according to those of your controller (evtest is your friend again). If your controller has a button to enable/disable analog sticks, make sure they're enabled.

[remap]
#Examples of Button => Key(s)
BTN_NORTH = ["KEY_LEFTMETA", "KEY_J"] #X
BTN_EAST = ["KEY_ENTER"] #A
BTN_SOUTH = ["KEY_LEFTSHIFT"] #B
BTN_WEST = ["KEY_LEFTMETA"] #Y
BTN_TR = ["KEY_LEFTMETA", "KEY_L"] #R (and SL on left joycon)
BTN_TL = ["KEY_LEFTMETA", "KEY_K"] #L (and SL on right joycon)
BTN_START = ["KEY_LEFTMETA", "KEY_D"] #plus
BTN_SELECT = ["KEY_ESC"] #minus
BTN_THUMBR = ["KEY_LEFTMETA", "KEY_Q"] #right stick press
BTN_THUMBL = ["BTN_MIDDLE"] #left stick press
BTN_MODE = ["KEY_SPACE"] #home
BTN_Z = ["BTN_LEFT"] #capture
#Examples of Axis events => Key(s)
BTN_TL2 = ["KEY_LEFTMETA", "KEY_LEFTSHIFT", "KEY_K"] #ZL (and SR on right joycon)
BTN_TR2 = ["KEY_LEFTMETA", "KEY_LEFTSHIFT", "KEY_L"] #ZR (and SR on left joycon)
BTN_DPAD_UP = ["KEY_UP"] #directional pad up
BTN_DPAD_RIGHT = ["KEY_RIGHT"] #directional pad right
BTN_DPAD_DOWN = ["KEY_DOWN"] #directional pad down
BTN_DPAD_LEFT = ["KEY_LEFT"] #directional pad left
RSTICK_UP = ["KEY_UP"] #right analog stick up
RSTICK_DOWN = ["KEY_DOWN"] #right analog stick down
RSTICK_LEFT = ["KEY_LEFT"] #right analog stick left
RSTICK_RIGHT = ["KEY_RIGHT"] #right analog stick right

[settings]
LSTICK_SENSITIVITY = "6" #sensitivity when scrolling or moving cursor, lower value is higher sensitivity, minimum 1
RSTICK_SENSITIVITY = "6" #sensitivity when scrolling or moving cursor, lower value is higher sensitivity, minimum 1
LSTICK = "cursor" #cursor, scroll, bind or disabled
RSTICK = "bind" #cursor, scroll, bind or disabled
LSTICK_DEADZONE = "5" #integer between 0 and 128, bigger number is wider deadzone, default 5
RSTICK_DEADZONE = "64" #integer between 0 and 128, bigger number is wider deadzone, default 5
16_BIT_AXIS = "true" #necessary for Xbox controllers and Switch joycons, use false for other controllers
GRAB_DEVICE = "false" #gain exclusivity on the device
