#SAMPLE CONFIG FILE FOR PLAYSTATION CONTROLLERS
#Put this in ~/.config/makita and rename it to the exact name of the device as shown by the 'evtest' command, including spaces and capitalization. Omit "/" if present.
#You can find all the available keycodes in /usr/include/linux/input-event-codes.h
#If you're not sure which keycode corresponds to which key, you can run 'evtest', select your device and press the corresponding key/button.
#Relative and absolute axis events are hard coded, for example use RSTICK_UP, RSTICK_DOWN etc to rebind your analog stick.
#This config file is tested for DualShock 3, DualShock 4 and DualSense controllers. When using a different controller, if no specific config file for your device is available, change the keycodes on the left according to those of your controller (evtest is your friend again). If your controller has a button to enable/disable analog sticks, make sure they're enabled.

[remap]
#Examples of Button => Key(s)
BTN_NORTH = ["KEY_LEFTMETA", "KEY_J"] #triangle
BTN_EAST = ["KEY_ENTER"] #circle
BTN_SOUTH = ["KEY_LEFTSHIFT"] #X
BTN_WEST = ["KEY_LEFTMETA"] #square
BTN_TR = ["KEY_LEFTMETA", "KEY_L"] #R1
BTN_TL = ["KEY_LEFTMETA", "KEY_K"] #L1
BTN_START = ["KEY_LEFTMETA", "KEY_D"] #start
BTN_SELECT = ["KEY_ESC"] #select
BTN_THUMBR = ["KEY_LEFTMETA", "KEY_Q"] #R3
BTN_THUMBL = ["BTN_MIDDLE"] #L3
BTN_MODE = ["KEY_SPACE"] #PS button
#Examples of Axis events => Key(s)
BTN_TL2 = ["KEY_LEFTMETA", "KEY_LEFTSHIFT", "KEY_K"] #L2
BTN_TR2 = ["KEY_LEFTMETA", "KEY_LEFTSHIFT", "KEY_L"] #R2
BTN_DPAD_UP = ["KEY_UP"] #directional pad up
BTN_DPAD_RIGHT = ["KEY_RIGHT"] #directional pad right
BTN_DPAD_DOWN = ["KEY_DOWN"] #directional pad down
BTN_DPAD_LEFT = ["KEY_LEFT"] #directional pad left
RSTICK_UP = ["KEY_UP"] #right analog stick up
RSTICK_DOWN = ["KEY_DOWN"] #right analog stick down

[settings]
LSTICK_SENSITIVITY = "6" #sensitivity when scrolling or moving cursor, lower value is higher sensitivity, minimum 1
RSTICK_SENSITIVITY = "6" #sensitivity when scrolling or moving cursor, lower value is higher sensitivity, minimum 1
LSTICK = "cursor" #cursor, scroll, bind or disabled
RSTICK = "bind" #cursor, scroll, bind or disabled
LSTICK_DEADZONE = "5" #integer between 0 and 128, bigger number is wider deadzone, default 5
RSTICK_DEADZONE = "64" #integer between 0 and 128, bigger number is wider deadzone, default 5
GRAB_DEVICE = "false" #gain exclusivity on the device
