#SAMPLE CONFIG FILE FOR A GENERIC KEYBOARD
#Put this in ~/.config/makita and rename it to the exact name of the device as shown by the 'evtest' command, including spaces and capitalization. Omit "/" if present.
#You can find the available keycodes in /usr/include/linux/input-event-codes.h
#If you're not sure which keycode corresponds to which key, you can run 'evtest', select your device and press the corresponding key/button.

[remap]
#Examples of Key => Key(s)
KEY_CAPSLOCK = ["KEY_LEFTCTRL"]
KEY_LEFTCTRL = ["KEY_CAPSLOCK"]
#Examples of Modifier(s) + Key => Key(s)
KEY_LEFTCTRL-KEY_LEFTSHIFT-KEY_Q = ["KEY_ESC"]
KEY_LEFTSHIFT-KEY_UP = ["KEY_LEFTSHIFT", "KEY_PAGEUP"]
KEY_LEFTSHIFT-KEY_DOWN = ["KEY_LEFTSHIFT", "KEY_PAGEDOWN"]
KEY_LEFTSHIFT-KEY_LEFTMETA-KEY_LEFTALT-KEY_RIGHT = ["KEY_LEFTCTRL", "KEY_C"]

[movements]
KEY_LEFTSHIFT-KEY_W = "CURSOR_UP"

[settings]
CUSTOM_MODIFIERS = "KEY_GRAVE-KEY_BACKSLASH" #The keys listed here will be treated as modifiers and will only emit their own event when released. If another key is pressed before the custom modifier is released, it will not emit any event. If you declare a binding that uses a non-modifier key as a modifier in the [remap] section, it's automatically added to this setting.
CURSOR_SPEED = "10" #Speed of the cursor when moved through keys specified in [movements].
CURSOR_ACCEL = "0.5" #Acceleration of the cursor when moved through keys. Values from 0.0 to 1.0.
