#SAMPLE CONFIG FILE FOR A GENERIC KEYBOARD
#Put this in ~/.config/makima and rename it to the exact name of the device as shown by the 'evtest' command, including spaces and capitalization. Omit "/" if present.
#You can find the available keycodes in /usr/include/linux/input-event-codes.h
#If you're not sure which keycode corresponds to which key, you can run 'evtest', select your device and press the corresponding key/button.

[remap]
#Examples of Key => Key(s)
KEY_CAPSLOCK = ["KEY_LEFTCTRL"]
KEY_LEFTCTRL = ["KEY_CAPSLOCK"]
#Examples of Modifier(s) + Key => Key(s)
KEY_LEFTCTRL-KEY_LEFTSHIFT-KEY_Q = ["KEY_ESC"]
KEY_LEFTSHIFT-KEY_UP = ["KEY_LEFTSHIFT", "KEY_PAGEUP"]
KEY_LEFTSHIFT-KEY_DOWN = ["KEY_LEFTSHIFT", "KEY_PAGEDOWN"]
KEY_LEFTSHIFT-KEY_LEFTMETA-KEY_LEFTALT-KEY_RIGHT = ["KEY_LEFTCTRL", "KEY_C"]

[commands]
#Examples of Modifier + Key => run a shell command
KEY_LEFTCTRL-KEY_N = ["nautilus"]
KEY_LEFTMETA-KEY_P = ["firefox", "discord"]
KEY_LEFTALT-KEY_SPACE = ["foot sh -c 'pacman -Q | wc -l && sleep 1 && neofetch' && sleep 5"]
KEY_LEFTCTRL-KEY_LEFTALT-KEY_LEFTSHIFT-KEY_O = ["notify-send 'OwO'"]
#You can also use non-modifier keys as Modifiers, and their behavior will be changed automatically to act as Modifiers (refer to the CUSTOM_MODIFIERS setting for more info).
KEY_MINUS-KEY_K = ["pkill firefox"]
#Keep in mind that if you want to use Modifiers across multiple devices (e.g. KEY_LEFTCTRL on your keyboard and BTN_RIGHT on your mouse), both devices will have to be read by Makima and thus both will need a config file, even if empty. Having a config file is just a way to tell Makima "Hey, read this device!".

[movements]
KEY_LEFTSHIFT-KEY_W = "CURSOR_UP"

[settings]
CUSTOM_MODIFIERS = "KEY_GRAVE-KEY_BACKSLASH" #The keys listed here will be treated as modifiers and will only emit their own event when released. If another key is pressed before the custom modifier is released, it will not emit any event. If you declare a binding that uses a non-modifier key as a modifier in the [remap] or [commands] sections, it's automatically added to this setting.
CURSOR_SPEED = "10" #Speed of the cursor when moved through keys specified in [movements].
CURSOR_ACCEL = "0.5" #Acceleration of the cursor when moved through keys. Values from 0.0 to 1.0.
