#SAMPLE CONFIG FILE FOR A GENERIC MOUSE
#Put this in ~/.config/makima and rename it to the exact name of the device as shown by the 'evtest' command, including spaces and capitalization. Omit "/" if present.
#You can find the available keycodes in /usr/include/linux/input-event-codes.h
#If you're not sure which keycode corresponds to which key, you can run 'evtest', select your device and press the corresponding key/button.
#Relative and absolute axis events are hard coded, for example use SCROLL_WHEEL_UP and SCROLL_WHEEL_DOWN to rebind wheel movements.

[remap]
#Example of Key => Key(s)
BTN_RIGHT = ["KEY_LEFTCTRL", "KEY_C"]
#Example of Axis event => Key(s)
SCROLL_WHEEL_UP = ["KEY_LEFTCTRL", "KEY_F"]
SCROLL_WHEEL_DOWN = ["KEY_LEFTCTRL", "KEY_Q"]
#Examples of Modifier(s) + Key => Key(s)
KEY_LEFTCTRL.BTN_RIGHT = ["KEY_SYSRQ"]
KEY_LEFTCTRL-KEY_LEFTSHIFT.BTN_LEFT = ["KEY_LEFTSHIFT", "KEY_DELETE"]
#Examples of Modifier(s) + Axis event => Key(s)
KEY_LEFTCTRL-KEY_LEFTSHIFT.SCROLL_WHEEL_UP = ["KEY_HOME"]
KEY_LEFTCTRL-KEY_LEFTSHIFT.SCROLL_WHEEL_DOWN = ["KEY_END"]
KEY_LEFTCTRL-KEY_LEFTSHIFT-KEY_LEFTALT.SCROLL_WHEEL_DOWN = ["KEY_LEFTALT", "KEY_F4"]

[settings]
GRAB_DEVICE = "true" #gain exclusivity on the device
