#SAMPLE CONFIG FILE FOR A GENERIC MOUSE
#Put this in ~/.config/makima and rename it to the exact name of the device as shown by the 'evtest' command, including spaces and capitalization.
#You can find all the available keycodes in /usr/include/linux/input-event-codes.h
#If you're not sure which keycode corresponds to which key, you can run 'evtest', select your keyboard/mouse and press the corresponding key/button.

[keys]
#MOUSE BUTTONS  MOUSE/KEYBOARD BINDINGS
BTN_RIGHT = ["KEY_LEFTCTRL", "KEY_C"]

[rel]
SCROLL_WHEEL_UP = ["KEY_LEFTCTRL", "KEY_LEFTSHIFT", "KEY_EQUAL"]
SCROLL_WHEEL_DOWN = ["KEY_LEFTCTRL", "KEY_MINUS"]

[settings]
GRAB_DEVICE = "true" #gain exclusivity on the device
