#SAMPLE CONFIG FILE FOR A GENERIC KEYBOARD
#Put this in ~/.config/makima and rename it to the exact name of the device as shown by the 'evtest' command, including spaces and capitalization.
#You can find all the available keycodes in /usr/include/linux/input-event-codes.h
#If you're not sure which keycode corresponds to which key, you can run 'evtest', select your keyboard/mouse and press the corresponding key/button.

[keys]
#KEYS	MOUSE/KEYBOARD BINDINGS
KEY_CAPSLOCK = ["KEY_LEFTCTRL"]
KEY_LEFTCTRL = ["KEY_CAPSLOCK"]

[settings]
GRAB_DEVICE = "true" #gain exclusivity on the device
